import type { Metadata } from "next";
import { Inter } from "next/font/google";
import NavBar from "./components/NavBar";
import { Montserrat } from "next/font/google";
import Footer from "./components/Footer";
//import "./globals.css";
const inter = Inter({ subsets: ["latin"] });

const montserrat = Montserrat({
  weight: "400",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }: any) {
  return (
    <html lang="pt-BR">
      <body
        className={(inter.className, montserrat.className)}
        style={{ padding: 0, margin: 0 }}
      >
        <NavBar />
        {children}
        <Footer />
      </body>
    </html>
  );
}
